### ISSUE TITLE
ModuleNotFoundError: No module named 'car'

### ISSUE THREAD

**Issue by amau457** [Hilicot/Neural_Network_NEAT#1]
hello, I'm very interested in your code, but I have a problem while executing it. An error message appears for each import from an other file from your files. I have downloded the zip, have extracted it and I put it on my Desktop in a folder. I haver never used import from other files , so I searched some documentation. I made some test but nothing worked. I'm using conda 3.7.3 with Pyzo. I tested to take python 3.7.0 but the error is still the same. Sorry for asking it here, but if you have a solution, please answer me !
have a nice day
Amaury

**Comment by marcporro** [comment]
I'm sorry you have this problem. I just used the normal python 3.7 build and it should work normally. I suggest you try to make a new simple file where you import a constant from a different one, to test the import mechanism, because it probably is a problem on your specific computer (other people have run it successfully)
